# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61ccd3f340b4106f7056dc07c5f8c992c773da9b8161b7e715c8a03fd23699eae2091ac4f8e62706d619ae2277077828e57990ea4eb6610bfca64f1f8cb04146

test:
  secret_key_base: ec51b1a243c62dcc0e6b9ad968a174437e4ca7b1fda60125b84a39c8c7ab526da899df4a08eaeafaaff41634f6f93d40e0be23876b05965f73724e2cce709d00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
